# Generated by Django 5.1 on 2024-08-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='otp',
            new_name='code',
        ),
    ]
