# Generated by Django 5.1 on 2024-08-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='code',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
