# Generated by Django 5.1 on 2024-08-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_driverprofile_passengerprofile_user_is_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_passenger',
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
        migrations.DeleteModel(
            name='PassengerProfile',
        ),
    ]
