# Generated by Django 5.1 on 2024-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_is_driver_user_is_passenger_driver_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_passenger',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
