# Generated by Django 5.1 on 2024-08-24 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_passenger_user_remove_user_is_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cidade', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('foto_rosto', models.ImageField(blank=True, null=True, upload_to='uploads/driver_photos/')),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('cnh_documento', models.FileField(blank=True, null=True, upload_to='uploads/driver_documents/')),
                ('veiculo_documento', models.FileField(blank=True, null=True, upload_to='uploads/vehicle_documents/')),
                ('placa_veiculo', models.CharField(max_length=10)),
                ('modelo_veiculo', models.CharField(max_length=50)),
                ('ano_veiculo', models.IntegerField()),
                ('cor_veiculo', models.CharField(max_length=20)),
                ('termo_aceite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/passenger_photos/')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10)),
                ('termo_aceite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(default=False),
        ),
    ]
