# Generated by Django 5.1 on 2024-08-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_driverprofile_passengerprofile_user_is_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='sobrenome',
        ),
    ]
