# Generated by Django 5.1 on 2024-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_driverprofile_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
