# Generated by Django 5.1 on 2024-08-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_driverprofile_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_approved',
        ),
    ]
