# Generated by Django 5.1 on 2024-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_driverprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
    ]
