# Generated by Django 5.1 on 2024-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_driverprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
