# Generated by Django 5.1 on 2024-08-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_driverlocation_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
