# Generated by Django 5.1 on 2024-08-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_driverprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
